waypoints:
  - position:
      x: 0.0
      y: 3.0
      z: 0.0
    orientation:
      Y: 0.0
  - position:
      x: 6.0
      y: 4.0
      z: 0.0
    orientation:
      Y: 0.523599
  - position:
      x: 6.5
      y: -1.4
      z: 0.0
    orientation:
      Y: 3.14159
  - position:
      x: -1.6
      y: -2.5
      z: 0.0
    orientation:
      Y: 1.308997