waypoints:
  - position:
      x: -9.15
      y: 4.30
      z: 0.0
    orientation:
      Y: 0.0
  - position:
      x: -6.93
      y: -3.69
      z: 0.0
    orientation:
      Y: 0.0
  - position:
      x: -3.58
      y: 0.06
      z: 0.0
    orientation:
      Y: 0.0
  - position:
      x: 3.90
      y: 0.14
      z: 0.0
    orientation:
      Y: 0.0
  - position:
      x: 3.41
      y: 4.10
      z: 0.0
    orientation:
      Y: 0.0
  - position:
      x: 9.43
      y: 4.31
      z: 0.0
    orientation:
      Y: 0.0
  - position:
      x: 9.43
      y: -4.61
      z: 0.0
    orientation:
      Y: 0.0  
  - position:
      x: 1.46
      y: -4.25
      z: 0.0
    orientation:
      Y: 0.0